-- ADMIN ONLY. STAGING ONLY. DISABLED TEMPLATE.
-- Never run from Flutter/client code. Never use production credentials.
-- This file targets only a human-approved disposable user in project pxtjkwfedrtnxuihtdox.
-- Do not execute until WALLET_ADMIN_SETUP_CONTRACT.md and WALLET_TEST_APPROVAL.md are approved.

-- Placeholders to replace only during an approved human-operated staging session:
-- {{USER_A_UUID}}                UUID of a confirmed disposable staging user
-- {{STARTING_CREDIT_AMOUNT}}     Positive integer baseline chosen by the approving operator
-- {{TRANSACTION_METADATA_JSON}}  JSON object identifying the staging fixture without secrets

-- SETUP (DISABLED): The exact columns below are from local migrations.
-- Preconditions: User A has no existing wallet or credit transactions, or a separately recorded
-- restoration plan exists. Do not overwrite a non-disposable user.
--
-- insert into public.monetization_wallets (
--   user_id, balance, allowance_remaining, bonus_balance, period_credits,
--   lifetime_earned, lifetime_spent, tier, period_ends_at, updated_at
-- ) values (
--   '{{USER_A_UUID}}'::uuid,
--   {{STARTING_CREDIT_AMOUNT}}, {{STARTING_CREDIT_AMOUNT}}, 0, {{STARTING_CREDIT_AMOUNT}},
--   {{STARTING_CREDIT_AMOUNT}}, 0, 'free', now() + interval '1 day', now()
-- );
--
-- Optional transaction fixture: use only if own-record visibility needs a pre-existing row.
-- insert into public.monetization_credit_transactions (
--   user_id, type, amount, balance_after, source, description, metadata
-- ) values (
--   '{{USER_A_UUID}}'::uuid, 'fixture', {{STARTING_CREDIT_AMOUNT}}, {{STARTING_CREDIT_AMOUNT}},
--   'staging_validation', 'Approved disposable wallet fixture', '{{TRANSACTION_METADATA_JSON}}'::jsonb
-- );

-- VERIFICATION (DISABLED): record results without exposing credentials.
-- select user_id, balance, allowance_remaining, bonus_balance, period_credits,
--        lifetime_earned, lifetime_spent, tier, period_ends_at
-- from public.monetization_wallets
-- where user_id = '{{USER_A_UUID}}'::uuid;
--
-- select id, user_id, type, amount, balance_after, source, description, metadata, created_at
-- from public.monetization_credit_transactions
-- where user_id = '{{USER_A_UUID}}'::uuid
-- order by created_at;

-- CLEANUP (DISABLED): only after all wallet/debit results are captured and only for a disposable user.
-- delete from public.monetization_credit_transactions
-- where user_id = '{{USER_A_UUID}}'::uuid
--   and source = 'staging_validation';
--
-- delete from public.monetization_wallets
-- where user_id = '{{USER_A_UUID}}'::uuid;
--
-- If any pre-existing state was present, do not use these deletes. Restore the recorded baseline
-- with a separately reviewed admin procedure instead.