import 'package:fantastic_guacamole/state/controllers/learning_controller.dart';
import 'package:fantastic_guacamole/state/controllers/ai_controller.dart';
import 'package:fantastic_guacamole/state/controllers/momentum_controller.dart';
import 'package:fantastic_guacamole/state/controllers/profile_controller.dart';
import 'package:fantastic_guacamole/state/controllers/si_state_controller.dart';
import 'package:fantastic_guacamole/state/controllers/voice_controller.dart';
import 'package:fantastic_guacamole/state/providers/repository_providers.dart';
import 'package:fantastic_guacamole/state/core/state_bootstrap.dart';
import 'package:fantastic_guacamole/state/providers/domain_usecase_providers.dart';
import 'package:fantastic_guacamole/state/providers/goals_provider.dart';
import 'package:fantastic_guacamole/state/providers/behavior_provider.dart';
import 'package:fantastic_guacamole/state/providers/assistant_release_provider.dart';
import 'package:fantastic_guacamole/state/providers/completion_score_provider.dart';
import 'package:fantastic_guacamole/state/providers/creator_draft_provider.dart';
import 'package:fantastic_guacamole/state/providers/creator_handshake_provider.dart';
import 'package:fantastic_guacamole/state/providers/decision_outcome_provider.dart';
import 'package:fantastic_guacamole/state/providers/first_use_context_offer_provider.dart';
import 'package:fantastic_guacamole/state/providers/emotion_provider.dart';
import 'package:fantastic_guacamole/state/providers/entitlement_provider.dart';
import 'package:fantastic_guacamole/state/providers/event_bus_provider.dart';
import 'package:fantastic_guacamole/state/providers/habits_provider.dart';
import 'package:fantastic_guacamole/state/providers/identity_provider.dart';
import 'package:fantastic_guacamole/state/providers/logs_provider.dart';
import 'package:fantastic_guacamole/state/providers/learning_history_provider.dart';
import 'package:fantastic_guacamole/state/providers/memories_provider.dart';
import 'package:fantastic_guacamole/state/providers/milestones_provider.dart';
import 'package:fantastic_guacamole/state/providers/notes_provider.dart';
import 'package:fantastic_guacamole/state/providers/notification_provider.dart';
import 'package:fantastic_guacamole/state/providers/optimization_provider.dart';
import 'package:fantastic_guacamole/state/providers/paywall_provider.dart';
import 'package:fantastic_guacamole/state/providers/person_context_provider.dart';
import 'package:fantastic_guacamole/state/providers/person_context_decision_provider.dart';
import 'package:fantastic_guacamole/state/providers/projects_provider.dart';
import 'package:fantastic_guacamole/state/providers/personalization_provider.dart';
import 'package:fantastic_guacamole/state/providers/routines_provider.dart';
import 'package:fantastic_guacamole/state/providers/si_console_thread_provider.dart';
import 'package:fantastic_guacamole/state/providers/si_memory_provider.dart';
import 'package:fantastic_guacamole/state/providers/si_pipeline_provider.dart';
import 'package:fantastic_guacamole/state/providers/service_providers.dart';
import 'package:fantastic_guacamole/state/providers/signals_provider.dart';
import 'package:fantastic_guacamole/state/providers/subtasks_provider.dart';
import 'package:fantastic_guacamole/state/providers/settings_ui_provider.dart';
import 'package:fantastic_guacamole/state/providers/sync_provider.dart';
import 'package:fantastic_guacamole/state/providers/task_provider.dart';
import 'package:fantastic_guacamole/state/providers/timeline_provider.dart';
import 'package:fantastic_guacamole/state/providers/trajectory_forecast_ledger_provider.dart';
import 'package:fantastic_guacamole/state/providers/trajectory_consequence_provider.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Disposes every provider that can retain account-owned values in memory.
/// Derived providers are invalidated transitively by these canonical roots.
void invalidateAccountOwnedProviders(Ref ref) {
  ref.invalidate(stateBootstrapProvider);
  ref.invalidate(tasksProvider);
  ref.invalidate(goalsProvider);
  ref.invalidate(habitsProvider);
  ref.invalidate(projectsProvider);
  ref.invalidate(routinesProvider);
  ref.invalidate(subtasksProvider);
  ref.invalidate(timelineProvider);
  ref.invalidate(creatorDraftPreviewProvider);
  ref.invalidate(creatorHandshakeProvider);
  ref.invalidate(memoriesProvider);
  ref.invalidate(logsProvider);
  ref.invalidate(milestonesProvider);
  ref.invalidate(profileProvider);
  ref.invalidate(identityStateProvider);
  ref.invalidate(learningProvider);
  ref.invalidate(siStateProvider);
  ref.invalidate(siMemoryProvider);
  ref.invalidate(smartPlannerMemoryProvider);
  ref.invalidate(aiResponseProvider);
  ref.invalidate(smartPlannerAiResponseProvider);
  ref.invalidate(aiInputProvider);
  ref.invalidate(smartPlannerAiInputProvider);
  ref.invalidate(aiAgentTraceProvider);
  ref.invalidate(smartPlannerAiAgentTraceProvider);
  ref.invalidate(aiExecutionStatusProvider);
  ref.invalidate(smartPlannerAiExecutionStatusProvider);
  ref.invalidate(siEngineStateProvider);
  ref.invalidate(smartPlannerEngineStateProvider);
  ref.invalidate(siEngineRepositoryProvider);
  ref.invalidate(siEngineServiceProvider);
  ref.invalidate(signalsBundleProvider);
  ref.invalidate(siConsoleThreadProvider);
  ref.invalidate(trajectoryForecastLedgerProvider);
  ref.invalidate(personalizationProfileProvider);
  ref.invalidate(personContextRepositoryProvider);
  ref.invalidate(personContextSpineProvider);
  ref.invalidate(personContextDecisionIgnoredSignalsProvider);
  ref.invalidate(personContextSettingsEntryProvider);
  ref.invalidate(firstUseContextOfferSeenProvider);
  ref.invalidate(observedPlanningPatternsProvider);
  ref.invalidate(cloudSyncPreferenceProvider);
  ref.invalidate(assistantBetaOptInProvider);
  ref.invalidate(assistantReleaseDecisionProvider);
  ref.invalidate(extendedDomainRepositoryProvider);
  ref.invalidate(extendedDomainBootstrapProvider);
  ref.invalidate(notesProvider);
  ref.invalidate(notificationProvider);
  ref.invalidate(behaviorStateProvider);
  ref.invalidate(optimizationConfigProvider);
  ref.invalidate(learningHistoryProvider);
  ref.invalidate(completionScoreProvider);
  ref.invalidate(decisionOutcomesProvider);
  ref.invalidate(decisionOutcomeRepositoryProvider);
  ref.invalidate(latestDecisionLearningChangeProvider);
  ref.invalidate(learningPausedProvider);
  ref.invalidate(learningRevisionProvider);
  ref.invalidate(domainLearningRepositoryProvider);
  ref.invalidate(siStateAggregationProvider);
  ref.invalidate(domainSiDecisionProvider);
  ref.invalidate(momentumProvider);
  ref.invalidate(emotionProvider);
  ref.invalidate(voiceControllerProvider);
  ref.invalidate(trajectoryHorizonDaysProvider);
  ref.invalidate(trajectoryCustomScenarioProvider);
  invalidateSignalPublicationState(ref);
  ref.invalidate(eventBusBootstrapProvider);
  ref.invalidate(eventBusProvider);

  ref.invalidate(appPaywallRepositoryProvider);
  ref.invalidate(paywallRepositoryProvider);
  ref.invalidate(getAvailablePlansUseCaseProvider);
  ref.invalidate(startSubscriptionUseCaseProvider);
  ref.invalidate(restorePurchasesUseCaseProvider);
  ref.invalidate(cancelSubscriptionUseCaseProvider);
  ref.invalidate(getPaywallConfigUseCaseProvider);
  ref.invalidate(getUserSubscriptionStateUseCaseProvider);
  ref.invalidate(checkEntitlementUseCaseProvider);
  ref.invalidate(paywallSubscriptionProvider);
  ref.invalidate(paywallConfigProvider);
  ref.invalidate(paywallPromptProvider);
  ref.invalidate(entitlementProvider);
  ref.invalidate(aiCreditWalletProvider);

  ref.invalidate(syncErrorMessageProvider);
  ref.invalidate(offlineSyncQueueProvider);
  ref.invalidate(syncServiceProvider);
  ref.invalidate(syncToCloudProvider);
  ref.invalidate(replayOfflineQueueProvider);
  ref.invalidate(offlineQueueCountProvider);
  ref.invalidate(restoreFromCloudProvider);

  ref.invalidate(getPlannerMessagesUseCaseProvider);
  ref.invalidate(savePlannerMessageUseCaseProvider);
  ref.invalidate(getSiQueriesExtendedUseCaseProvider);
  ref.invalidate(saveSiQueryExtendedUseCaseProvider);
  ref.invalidate(getReflectionEntriesUseCaseProvider);
  ref.invalidate(saveReflectionEntryUseCaseProvider);
  ref.invalidate(getAnalyticsMetricsUseCaseProvider);
  ref.invalidate(saveAnalyticsMetricUseCaseProvider);
  ref.invalidate(getExtendedAppSettingsUseCaseProvider);
  ref.invalidate(saveExtendedAppSettingUseCaseProvider);
}
