// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9H-X2VmhFAFb8IuHS7KyC7V3G5EM2154',
    appId: '1:956622397052:web:4e4d7b8ddd6c8b6c9133f9',
    messagingSenderId: '956622397052',
    projectId: 'chronospark-app',
    authDomain: 'chronospark-app.firebaseapp.com',
    storageBucket: 'chronospark-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEdXHOa-AZLTDCi97SBqD4fAvH3vdnneU',
    appId: '1:956622397052:android:3ecf5fcda0f2e1ef9133f9',
    messagingSenderId: '956622397052',
    projectId: 'chronospark-app',
    storageBucket: 'chronospark-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeDIlk349AqTLueWvfnD_PDKlQ4IsOXnY',
    appId: '1:956622397052:ios:ae0e18f5cc5a6c459133f9',
    messagingSenderId: '956622397052',
    projectId: 'chronospark-app',
    storageBucket: 'chronospark-app.firebasestorage.app',
    iosBundleId: 'com.example.chronospark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeDIlk349AqTLueWvfnD_PDKlQ4IsOXnY',
    appId: '1:956622397052:ios:ae0e18f5cc5a6c459133f9',
    messagingSenderId: '956622397052',
    projectId: 'chronospark-app',
    storageBucket: 'chronospark-app.firebasestorage.app',
    iosBundleId: 'com.example.chronospark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9H-X2VmhFAFb8IuHS7KyC7V3G5EM2154',
    appId: '1:956622397052:web:82a60d93afaffeda9133f9',
    messagingSenderId: '956622397052',
    projectId: 'chronospark-app',
    authDomain: 'chronospark-app.firebaseapp.com',
    storageBucket: 'chronospark-app.firebasestorage.app',
  );
}
