// ChronoSpark FirebaseOptions
// Generated by `flutterfire configure` for project: chronospark-app.
// This file is stable and does not change across environments.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ------------------------------------------------------------
  // WEB
  // ------------------------------------------------------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBEdXHOa-AZLTDCi97SBqD4fAvH3vdnneU",
    appId: "1:956622397052:web:31f23707a15bf8f19133f9",
    messagingSenderId: "956622397052",
    projectId: "chronospark-app",
    authDomain: "chronospark-app.firebaseapp.com",
    storageBucket: "chronospark-app.firebasestorage.app",
  );

  // ------------------------------------------------------------
  // ANDROID
  // ------------------------------------------------------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBEdXHOa-AZLTDCi97SBqD4fAvH3vdnneU",
    appId: "1:956622397052:android:3ecf5fcda0f2e1ef9133f9",
    messagingSenderId: "956622397052",
    projectId: "chronospark-app",
    storageBucket: "chronospark-app.firebasestorage.app",
  );

  // ------------------------------------------------------------
  // iOS
  // ------------------------------------------------------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBEdXHOa-AZLTDCi97SBqD4fAvH3vdnneU",
    appId: "1:956622397052:ios:4a522f3f234d24959133f9",
    messagingSenderId: "956622397052",
    projectId: "chronospark-app",
    iosBundleId: "com.ghostheart5.chronospark",
    storageBucket: "chronospark-app.firebasestorage.app",
  );

  // ------------------------------------------------------------
  // macOS
  // ------------------------------------------------------------
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBEdXHOa-AZLTDCi97SBqD4fAvH3vdnneU",
    appId: "1:956622397052:ios:ae0e18f5cc5a6c459133f9",
    messagingSenderId: "956622397052",
    projectId: "chronospark-app",
    iosBundleId: "com.example.chronospark",
    storageBucket: "chronospark-app.firebasestorage.app",
  );

  // ------------------------------------------------------------
  // WINDOWS
  // ------------------------------------------------------------
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBEdXHOa-AZLTDCi97SBqD4fAvH3vdnneU",
    appId: "1:956622397052:web:31f23707a15bf8f19133f9",
    messagingSenderId: "956622397052",
    projectId: "chronospark-app",
    storageBucket: "chronospark-app.firebasestorage.app",
  );
}
