-- Store only explicit user reports of generated responses. The table is not
-- exposed to client roles; the authenticated Edge Function inserts reports
-- with the service role after verifying the caller's JWT.
create table if not exists public.ai_content_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in (
    'unsafe_or_harmful',
    'misleading_or_inaccurate',
    'privacy_concern',
    'other'
  )),
  content text not null check (char_length(content) between 1 and 4000),
  source text not null default 'si_console',
  status text not null default 'new' check (status in ('new', 'reviewed', 'closed')),
  created_at timestamptz not null default now()
);

alter table public.ai_content_reports enable row level security;
revoke all on table public.ai_content_reports from anon, authenticated;

create index if not exists ai_content_reports_created_at_idx
  on public.ai_content_reports (created_at desc);

create index if not exists ai_content_reports_user_id_idx
  on public.ai_content_reports (user_id);
