import 'package:fantastic_guacamole/core/storage/account_storage_scope.dart';
import 'package:fantastic_guacamole/state/providers/account_storage_scope_provider.dart';
import 'package:fantastic_guacamole/state/providers/domain_usecase_providers.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('shipping domain repository and use-case graph constructs stably', () {
    final ProviderContainer container = ProviderContainer(
      overrides: [
        accountStorageScopeProvider.overrideWithValue(
          AccountStorageScope.authenticated('composition-test-account'),
        ),
      ],
    );
    addTearDown(container.dispose);

    final List<Object Function()> bindings = <Object Function()>[
      () => container.read(domainTaskRepositoryProvider),
      () => container.read(domainNotificationRepositoryProvider),
      () => container.read(domainGoalRepositoryProvider),
      () => container.read(domainSignalRepositoryProvider),
      () => container.read(domainLogRepositoryProvider),
      () => container.read(domainMemoryRepositoryProvider),
      () => container.read(domainNoteRepositoryProvider),
      () => container.read(domainMilestoneRepositoryProvider),
      () => container.read(domainPlanRepositoryProvider),
      () => container.read(domainProjectRepositoryProvider),
      () => container.read(domainProfileRepositoryProvider),
      () => container.read(domainProgressionRepositoryProvider),
      () => container.read(domainRoutineRepositoryProvider),
      () => container.read(domainSubtaskRepositoryProvider),
      () => container.read(domainTimelineRepositoryProvider),
      () => container.read(domainThemeRepositoryProvider),
      () => container.read(domainIdentityRepositoryProvider),
      () => container.read(domainSiRepositoryProvider),
      () => container.read(domainCalendarRepositoryProvider),
      () => container.read(domainSettingsRepositoryProvider),
      () => container.read(domainWorkspaceRepositoryProvider),
      () => container.read(domainLearningRepositoryProvider),
      () => container.read(extendedDomainRepositoryProvider),
      () => container.read(domainHabitRepositoryProvider),
      () => container.read(getPlannerMessagesUseCaseProvider),
      () => container.read(savePlannerMessageUseCaseProvider),
      () => container.read(getSiQueriesExtendedUseCaseProvider),
      () => container.read(saveSiQueryExtendedUseCaseProvider),
      () => container.read(getReflectionEntriesUseCaseProvider),
      () => container.read(saveReflectionEntryUseCaseProvider),
      () => container.read(getAnalyticsMetricsUseCaseProvider),
      () => container.read(saveAnalyticsMetricUseCaseProvider),
      () => container.read(getExtendedAppSettingsUseCaseProvider),
      () => container.read(saveExtendedAppSettingUseCaseProvider),
      () => container.read(getTasksUseCaseProvider),
      () => container.read(getGoalsUseCaseProvider),
      () => container.read(getSignalsUseCaseProvider),
      () => container.read(addSignalUseCaseProvider),
      () => container.read(generateSignalFromEventUseCaseProvider),
      () => container.read(getLogsUseCaseProvider),
      () => container.read(addLogEntryUseCaseProvider),
      () => container.read(getCurrentThemeUseCaseProvider),
      () => container.read(saveThemeUseCaseProvider),
      () => container.read(getAllThemesUseCaseProvider),
      () => container.read(switchThemeUseCaseProvider),
      () => container.read(getIdentityProfileUseCaseProvider),
      () => container.read(saveIdentityProfileUseCaseProvider),
      () => container.read(createGoalUseCaseProvider),
      () => container.read(updateGoalUseCaseProvider),
      () => container.read(deleteGoalUseCaseProvider),
      () => container.read(completeGoalUseCaseProvider),
      () => container.read(saveGoalsUseCaseProvider),
      () => container.read(getProjectsUseCaseProvider),
      () => container.read(createProjectUseCaseProvider),
      () => container.read(updateProjectUseCaseProvider),
      () => container.read(deleteProjectUseCaseProvider),
      () => container.read(saveProjectsUseCaseProvider),
      () => container.read(getRoutinesUseCaseProvider),
      () => container.read(createRoutineUseCaseProvider),
      () => container.read(updateRoutineUseCaseProvider),
      () => container.read(deleteRoutineUseCaseProvider),
      () => container.read(saveRoutinesUseCaseProvider),
      () => container.read(getSubtasksUseCaseProvider),
      () => container.read(createSubtaskUseCaseProvider),
      () => container.read(updateSubtaskUseCaseProvider),
      () => container.read(deleteSubtaskUseCaseProvider),
      () => container.read(saveSubtasksUseCaseProvider),
      () => container.read(getMemoriesUseCaseProvider),
      () => container.read(saveMemoryUseCaseProvider),
      () => container.read(deleteMemoryUseCaseProvider),
      () => container.read(saveMemoriesUseCaseProvider),
      () => container.read(getPlanUseCaseProvider),
      () => container.read(createPlanUseCaseProvider),
      () => container.read(updatePlanUseCaseProvider),
      () => container.read(generateAdaptivePlanUseCaseProvider),
      () => container.read(analyzePlanContextUseCaseProvider),
      () => container.read(recommendNextBlockUseCaseProvider),
      () => container.read(scoreTasksUseCaseProvider),
      () => container.read(extractSiSignalsUseCaseProvider),
      () => container.read(assembleSiContextUseCaseProvider),
      () => container.read(assembleSiDecisionOutputUseCaseProvider),
      () => container.read(getHabitsUseCaseProvider),
      () => container.read(createHabitUseCaseProvider),
      () => container.read(toggleHabitUseCaseProvider),
      () => container.read(updateHabitUseCaseProvider),
      () => container.read(deleteHabitUseCaseProvider),
      () => container.read(saveHabitsUseCaseProvider),
      () => container.read(getProfileUseCaseProvider),
      () => container.read(getProgressionUseCaseProvider),
      () => container.read(updateStreakUseCaseProvider),
      () => container.read(updateXpUseCaseProvider),
      () => container.read(updateLevelUseCaseProvider),
      () => container.read(awardXpUseCaseProvider),
      () => container.read(getUserLevelUseCaseProvider),
      () => container.read(getSettingsUseCaseProvider),
      () => container.read(updateSettingsUseCaseProvider),
      () => container.read(getWorkspaceUseCaseProvider),
      () => container.read(switchWorkspaceUseCaseProvider),
      () => container.read(getCalendarEntriesUseCaseProvider),
      () => container.read(addCalendarEntryUseCaseProvider),
      () => container.read(removeCalendarEntryUseCaseProvider),
      () => container.read(hydrateSiStateUseCaseProvider),
      () => container.read(updateSiStateUseCaseProvider),
      () => container.read(applyLearningFeedbackUseCaseProvider),
      () => container.read(updateLearningStateUseCaseProvider),
      () => container.read(skipTaskUseCaseProvider),
      () => container.read(getTimelineEventsUseCaseProvider),
      () => container.read(addTimelineEventUseCaseProvider),
      () => container.read(removeTimelineEventUseCaseProvider),
      () => container.read(saveTimelineEventsUseCaseProvider),
      () => container.read(queryTimelineRangeUseCaseProvider),
      () => container.read(scheduleTimelineEventUseCaseProvider),
      () => container.read(rescheduleTimelineEventUseCaseProvider),
      () => container.read(completeTimelineEventUseCaseProvider),
      () => container.read(skipTimelineEventUseCaseProvider),
      () => container.read(recoverTimelineEventUseCaseProvider),
      () => container.read(previewAdaptivePlanUseCaseProvider),
      () => container.read(applyPlanProposalUseCaseProvider),
      () => container.read(rejectPlanProposalUseCaseProvider),
      () => container.read(createTaskUseCaseProvider),
      () => container.read(completeTaskUseCaseProvider),
      () => container.read(updateTaskUseCaseProvider),
      () => container.read(deleteTaskUseCaseProvider),
      () => container.read(scheduleNotificationUseCaseProvider),
      () => container.read(cancelNotificationUseCaseProvider),
      () => container.read(getNotesUseCaseProvider),
      () => container.read(createNoteUseCaseProvider),
      () => container.read(updateNoteUseCaseProvider),
      () => container.read(archiveNoteUseCaseProvider),
      () => container.read(deleteNoteUseCaseProvider),
      () => container.read(getMilestonesUseCaseProvider),
      () => container.read(createMilestoneUseCaseProvider),
      () => container.read(updateMilestoneUseCaseProvider),
      () => container.read(updateMilestoneProgressUseCaseProvider),
      () => container.read(completeMilestoneUseCaseProvider),
      () => container.read(archiveMilestoneUseCaseProvider),
      () => container.read(deleteMilestoneUseCaseProvider),
      () => container.read(generateSiDecisionUseCaseProvider),
    ];

    expect(bindings, hasLength(greaterThan(125)));
    for (final Object Function() readBinding in bindings) {
      final Object first = readBinding();
      expect(first, isNotNull);
      expect(readBinding(), same(first));
    }
  });
}
